<a href="https://colab.research.google.com/github/patgzyl/data-science/blob/master/01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a=np.array([[1,2,3],[4,4,4]])
print(a)

[[1 2 3]
 [4 4 4]]


In [21]:
np.random.randn(10, 4)
np.random.rand(10,4)
a=np.random.randint(1,10,100)
np.random.choice(a)
b=np.arange(10)
b=np.random.shuffle(b)

None


In [30]:
A=np.random.rand(10)
np.argmax(A)
A[np.argmax(A)]
np.argsort(A)
np.mean(A)

0.45848965918837764

In [7]:
A=np.arange(-10,10,0.5)
A=A.reshape(10,-1)
A>0
A[A>0]
np.bitwise_and(A>-5,A<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])