<a href="https://colab.research.google.com/github/patgzyl/data-science/blob/master/02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [4]:
v1=np.array([1,4])
np.linalg.norm(v1)

4.123105625617661

In [5]:
a=np.array([1,5,7])
b=np.array([3,7,0])
np.linalg.norm(a-b)

7.54983443527075

In [13]:
X=np.array([[1,4],[-2,2]])
Y=np.array([[1],[-1]])
X@Y
Z=np.dot(X,Y)
Z.shape


ValueError: ignored

In [16]:
A=np.array([[1,4,5,6],[3,-8,-1,0],[1,4,5,-4],[1,-9,0,4]])
np.linalg.det(A)
round(np.linalg.det(A))

-1080.0

In [18]:
np.trace(A)

2

In [19]:
np.eye(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [24]:
B=np.linalg.inv(A)
np.set_printoptions(precision=4,suppress=True)
Z=np.dot(A,B)
Z

array([[ 1.,  0.,  0., -0.],
       [-0.,  1., -0.,  0.],
       [-0.,  0.,  1., -0.],
       [ 0., -0.,  0.,  1.]])

In [28]:
np.transpose(A)

array([[ 1,  3,  1,  1],
       [ 4, -8,  4, -9],
       [ 5, -1,  5,  0],
       [ 6,  0, -4,  4]])

In [30]:
A=np.array([[2,4],[1,-1]])
B=np.array([[10],[-1]])
A_inv=np.linalg.inv(A)
X=np.dot(A_inv,B)
X

array([[1.],
       [2.]])